name: open_close_loop_recycling
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  form_field_validator: ^1.1.0
  flutter_svg: ^1.1.6
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.0
  uuid: ^3.0.7
  firebase_core: ^2.4.0
  flutter_web_browser: ^0.17.1
  connectivity_plus: ^3.0.2
  google_maps_flutter: ^2.2.3   
  geolocator: 
  geocoding:
  badges: ^3.0.3
  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
